#Numpy는 할 수 있지만 일반 리스트는 할 수 없는것

In [17]:
#일반 list에서는 모두 일괄적인 계산이 어렵다.고로 에러가 뜬다!
height = [1.73,1.68,1.71,1.89,1.79]
weight = [65.4,56.7,33.6,66.5,34.6]
weight / height ** 2 

TypeError: ignored

In [18]:
#Numpy는 작업방법을 알고 있어 쉽게 계산할 수 있다.
import numpy as np
np_height = np.array(height)
np_weight = np.array(weight)
np_weight / np_height ** 2

array([21.85171573, 20.08928571, 11.49071509, 18.6165001 , 10.79866421])

#Numpy Subsetting & Numpy Side Effects

In [19]:
#Numpy는 오직 한 종류의 type만 가능하다(유형이 다른 요소를 포함할 수 없다)
#자동으로 타입을 동일하게 변환해준다.
np.array([1.0,"is", True])

array(['1.0', 'is', 'True'], dtype='<U32')

In [20]:
#자동으로 구현되는 Numpy만의 메소드가 존재한다.
python_List = [1,2,3]
numpy_array = np.array([1,2,3])

print(python_List + python_List)

print(numpy_array + numpy_array)

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [21]:
#이렇게도 원하는 결과값을 확인 할 수 있다.
bmi= np.array([21.456,23.444,56.333,13.455])
print(bmi[1])

print(bmi > 23) #불린값을 구할 수 있다

print(bmi[bmi > 23]) #불린값을 통해 요소를 프린트할 수 있다.


23.444
[False  True  True False]
[23.444 56.333]


##파이썬 리스트와 넘파이의 차이

In [22]:
#넘파이 배열에 사용되는 연산자는 배열의 모든 요소에 개별적으로 연산이 적용된다!
list_data = [1,2,3,4]
array_data = np.array([1,2,3,4])

#파이썬 리스트는 곱셈 연산자를 만나면 지정된 횟수만큼 리스트의 요소를 반복하는 리스트를 만드므로 길이가 두배로 늘어난다.
print('파이썬 리스트 곱셈 연산 결과: {}'.format(list_data * 2))
print('넘파이 배열 곱셈 연산 결과:{}'.format(array_data * 2))

파이썬 리스트 곱셈 연산 결과: [1, 2, 3, 4, 1, 2, 3, 4]
넘파이 배열 곱셈 연산 결과:[2 4 6 8]


##넘파이의 다양한 함수모음

In [23]:
import numpy as np

one_point=np.array([1,2,3,4,5,6])
print(one_point.dtype) #자료형을 출력해준다

one_point.astype(str) #해당 형식으로 변경

one_1 = np.arange(10) #0번부터 인덱스 순서대로 값을 넣는다
print(one_1)

one_2 = np.arange(0, 10, 0.5) #0부터 9.5까지 0.5 간격으로 
print(one_2)

one_3 = np.arange(20).reshape(4,5) #0부터 인덱스 20까지 reshape를 통해 행과 열 설정해줌
print(one_3)
# np.reshape(행,열) #특정 배열을 행,열에 맞춰서 배치한다.

np.zeros((3,4)) #모든 값을 0으로 채운다.

int64
[0 1 2 3 4 5 6 7 8 9]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])